import fs from 'node:fs';
import path from 'node:path';
import { CliError } from './errors.js';
import { runCommandCapture } from './process.js';
import type { CliConfig } from './types.js';

const WRANGLER_ENV_INTERFACE = 'BetterCfWranglerEnv';

export interface EnvTypeResult {
  wranglerEnvPath: string;
  autoEnvPath: string;
}

export async function generateEnvTypes(config: CliConfig): Promise<EnvTypeResult> {
  const outDir = path.join(config.rootDir, '.better-cf');
  fs.mkdirSync(outDir, { recursive: true });

  const wranglerEnvPath = path.join(outDir, 'wrangler-env.d.ts');
  const autoEnvPath = path.join(outDir, 'auto-env.d.ts');

  const skipWrangler = process.env.BETTER_CF_SKIP_WRANGLER_TYPES === '1' || config.inferEnvTypes === false;

  if (skipWrangler) {
    fs.writeFileSync(
      wranglerEnvPath,
      `// Auto-generated fallback when wrangler types is skipped.\ninterface ${WRANGLER_ENV_INTERFACE} {\n  [key: string]: unknown;\n}\n`,
      'utf8'
    );
  } else {
    const command = await runCommandCapture(
      'npx',
      ['wrangler', 'types', '--path', wranglerEnvPath, '--env-interface', WRANGLER_ENV_INTERFACE],
      config.rootDir
    );

    if (command.code !== 0) {
      throw new CliError({
        code: 'WRANGLER_TYPES_FAILED',
        summary: 'Failed to infer env types with wrangler.',
        details: command.stderr || command.stdout || `Exit code ${command.code}`,
        hint: 'Install wrangler >=3.91 and verify wrangler config is valid.',
        docsUrl: 'https://developers.cloudflare.com/workers/wrangler/commands/#types'
      });
    }

    if (!fs.existsSync(wranglerEnvPath)) {
      throw new CliError({
        code: 'WRANGLER_TYPES_OUTPUT_MISSING',
        summary: 'Wrangler types command succeeded but output file was not created.',
        file: wranglerEnvPath,
        hint: 'Check wrangler CLI version and project permissions.'
      });
    }
  }

  fs.writeFileSync(
    autoEnvPath,
    `// Auto-generated by better-cf. Do not edit.\n/// <reference path=\"./wrangler-env.d.ts\" />\n\ndeclare module 'better-cf/queue' {\n  interface BetterCfAutoEnv extends BetterCfGeneratedBindings, ${WRANGLER_ENV_INTERFACE} {}\n}\n\nexport {};\n`,
    'utf8'
  );

  return {
    wranglerEnvPath,
    autoEnvPath
  };
}
